# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba2255f3969f6af6c7f74ad89a46253f7bed68b1132078bbedb5d6da22c261f3efeb60c0d182be9b343baf080981360c7e3bdfd7864d0d548a41f78fc8e605a8

test:
  secret_key_base: 06d8227d203a0cc986fd8799916a613987a4d8f8e49de7ebce08722080fe70d55895fc2190ff011107c6e704521c9d6c98c9ac189f7aa3d7c9374dd87bd2953b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
